[versions]
agp = "8.13.1"
firebaseBom = "34.6.0"
composeBom = "2025.11.01"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
appcompat = "1.7.1"
glance = "1.1.1"
gson = "2.13.2"
navigationKtx = "2.9.6"
coil = "2.7.0"
composeMarkdown = "0.3.5"
rollingnumbers = "0.0.7"
shimmer = "1.3.3"
vico = "2.3.6"
lifecycle = "2.10.0"
okhttp = "5.3.2"
composeActivity = "1.12.0"
googleGmsGoogleServices = "4.4.4"
chucker = "4.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-inappmessaging-display = { module = "com.google.firebase:firebase-inappmessaging-display" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "composeActivity" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationKtx" }
compose-coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
compose-markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "composeMarkdown" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationKtx" }
rollingnumbers = { module = "com.github.delacrixmorgan.rollingnumbers:lib", version.ref = "rollingnumbers" }
shimmer = { group = "com.valentinilk.shimmer", name = "compose-shimmer", version.ref = "shimmer" }
vico = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
lifecycle-runtimeKtx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
